# -*- coding: utf-8 -*-
"""Sample_GitHub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WiI_TWHa8on3YvG6AJCQYnFP04nblF-3
"""

import pandas as pd
import numpy as np

print("Hello Capstone Project Course!")